#!/bin/bash/env python

#SOLVED

#Each new term in the Fibonacci sequence is generated by adding the previous
#two terms. By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

def method1():
    (i, j) = 1, 1
    sum = 0
    while sum <= 4000000:
        if j & 1 == 0:
            sum += j
        (i, j) = (j, i + j)
    print("Method 1: ", sum)

if (__name__ == '__main__'):
    method1()
